## LinearRegression

In [9]:
from sklearn.linear_model import LinearRegression

X = [[10.0], [8.0], [13.0], [9.0], [11.0], [14.0],[6.0], [4.0], [12.0], [7.0], [5.0]]
y = [8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26, 10.84, 4.82, 5.68]

model = LinearRegression()
model.fit(X, y)
print('bias: ',model.intercept_) # 截距
print('weight: ',model.coef_[0])  # 斜率
y_pred = model.predict([[0], [1]])  # 对x=0,x=1的预测结果
print(f'x=0: {y_pred[0]}, x=1: {y_pred[1]}')

bias:  3.0000909090909103
weight:  0.5000909090909091
x=0: 3.0000909090909103, x=1: 3.5001818181818196


## LogisticRegression

In [5]:
import numpy as np
from sklearn.linear_model import LogisticRegression

# np.r_ 按行堆叠
X_train = np.r_[np.random.normal(3, 1, size=50), np.random.normal(-1, 1, size=50)].reshape((100, -1))
y_train = np.r_[np.ones(50), np.zeros(50)]

model = LogisticRegression()
model.fit(X_train, y_train)
print(model.predict([[0], [1], [2]]))
print(model.predict_proba([[0], [1], [2]])[:, 1])

[0. 1. 1.]
[0.1154632  0.58354654 0.93766158]


## Support Vector Machine

### 线性方法（直线的决策边界）

In [11]:
from sklearn.svm import LinearSVC
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 生成数据
centers = [(-1, -0.125), (0.5, 0.5)]
X, y = make_blobs(n_samples=50, n_features=2, centers=centers, cluster_std=0.3)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

model = LinearSVC()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(y_pred, y_test)
print(accuracy_score(y_pred, y_test))

[0 1 1 0 1 0 0 0 1 1 1 0 1 0 1] [0 1 1 0 1 0 0 0 1 1 1 0 1 0 1]
1.0


### 核方法 kernel
默认使用RBF(Radial Basic Funtion, 径向基函数)

In [18]:
from sklearn.svm import SVC
from sklearn.datasets import make_gaussian_quantiles
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 生成数据
centers = [(-1, -0.125), (0.5, 0.5)]
X, y = make_gaussian_quantiles(n_samples=300, n_features=2, n_classes=2)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

model = SVC()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(y_pred)
print(y_test)
print(accuracy_score(y_pred, y_test))

[1 1 0 0 1 1 0 0 1 1 1 1 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 1
 1 0 1 1 0 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 1 1 0 0 0 1 0 0 1 1 0 0
 1 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0]
[1 1 0 0 1 1 0 0 1 1 1 1 0 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 1 1
 1 0 1 1 0 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 1 1 0 0 0 1 1 0 1 1 0 0
 1 0 0 0 0 0 1 0 1 1 1 1 1 1 0 0]
0.9666666666666667


## Random Forest

In [29]:
from sklearn.datasets import load_wine
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

data = load_wine()
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.3)

model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy_score(y_pred, y_test)

0.9814814814814815

## Neural Network

In [41]:
from sklearn.datasets import load_digits
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

data = load_digits()
X = data.images.reshape(len(data.images), -1)
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

model = MLPClassifier(hidden_layer_sizes=(16, ), max_iter=450)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy_score(y_pred, y_test)

0.9648148148148148

## KNN(k-Nearest Neighbor)

In [57]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X, y = make_moons(noise=0.3)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# 最近邻点k的值默认为5
model = KNeighborsClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy_score(y_pred, y_test)

0.9333333333333333